package com.model;
// Generated 08 7, 15 10:09:21 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HrmsEmployeeDetails generated by hbm2java
 */
@Entity
@Table(name = "hrms_employee_details", catalog = "hrms")
public class HrmsEmployeeDetails implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int empId;
	private String firstName;
	private String lastName;
	private String midName;
	private Date birthDate;
	private int age;
	private String sex;
	private String address;
	private Date employedDate;
	private int supervisorId;
	private Set<HrmsLogin> hrmsLogins = new HashSet<HrmsLogin>(0);

	@Id
	@Column(name = "empId", unique = true, nullable = false)
	public int getEmpId() {
		return this.empId;
	}

	public void setEmpId(int empId) {
		this.empId = empId;
	}

	@Column(name = "firstName", nullable = false, length = 50)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "lastName", nullable = false, length = 50)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "midName", nullable = false, length = 50)
	public String getMidName() {
		return this.midName;
	}

	public void setMidName(String midName) {
		this.midName = midName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birthDate", nullable = false, length = 10)
	public Date getBirthDate() {
		return this.birthDate;
	}

	public void setBirthDate(Date birthDate) {
		this.birthDate = birthDate;
	}

	@Column(name = "age", nullable = false)
	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	@Column(name = "sex", nullable = false, length = 2)
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@Column(name = "address", nullable = false, length = 100)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "employedDate", nullable = false, length = 10)
	public Date getEmployedDate() {
		return this.employedDate;
	}

	public void setEmployedDate(Date employedDate) {
		this.employedDate = employedDate;
	}

	@Column(name = "supervisorId", nullable = false)
	public int getSupervisorId() {
		return this.supervisorId;
	}

	public void setSupervisorId(int supervisorId) {
		this.supervisorId = supervisorId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hrmsEmployeeDetails")
	public Set<HrmsLogin> getHrmsLogins() {
		return this.hrmsLogins;
	}

	public void setHrmsLogins(Set<HrmsLogin> hrmsLogins) {
		this.hrmsLogins = hrmsLogins;
	}

}
